config/routes.rb
Rails.application.routes.draw do
  get 'relations/create'
  get 'relations/show'
  get 'relations/destroy'
  mount Ckeditor::Engine => '/ckeditor' if Gem.loaded_specs.has_key? "ckeditor"
  resources :libraries
  resources :comments
  resources :posts
  
  root 'posts#index'
  
  get 'posts' => "post#show"
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "login" => "sessions#index"
  get "libraries" => "libraries#index"
  get "tag" => "tags#index"
  get "events" => "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/library.rb
class Library < ApplicationRecord
    
    has_many :relations

    
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action #:require_signin!, only: [:new]
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:title, :description, :link, :file_upload, :tags)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :file_upload %>
    <%= cktext_area :file_upload, cols: 40 %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libraries</h1>

<div class="container">
  <div class="row text-center">
    <div id="tag_box" class="col-md-3 well"></div>

  <%= link_to new_library_path do %>
    <div class="library_source col-md-2" id="newresource">New Resource<br><span class="glyphicon glyphicon-plus"></span>
    </div>
  <% end %>  

   <% @libraries.each do |library| %>
      <div class="library_source col-md-2">
        <%= link_to library do %>
            <h2><%= library.title %></h2>
            <h6><%= library.description %></h6>
        <% end %>
            <p>#<%= library.tags %></p>
            <p><%= link_to 'Show', library %>
              <%= link_to 'Edit', edit_library_path(library) %>
              <%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>

   <% end %>

  </div>
</div>

<br>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
  <div class="container">
    <div class="well">
        <h3>
          <strong>Title:</strong>
          <%= @library.title %>
        </h3>
        <p>
          <strong>Description:</strong>
          <%= @library.description %>
        </p>
         <p>
          <strong>Tags:</strong>
          <%= @library.tags %>
        </p>

        <%= link_to 'Edit', edit_library_path(@library) %> 
        <%= link_to 'Back', libraries_path %> 
    </div>
    <div class="well">
        <p>
          <strong>Link:</strong>
          <%= @library.link %>
        </p>

        <p>
          <strong>File upload:</strong>
          <%= @library.file_upload %>
        </p>

    
    </div>
  </div>
</div>