config/routes.rb
Rails.application.routes.draw do
  get 'relations/create'
  get 'relations/show'
  get 'relations/destroy'
  mount Ckeditor::Engine => '/ckeditor' if Gem.loaded_specs.has_key? "ckeditor"
  resources :libraries
  resources :comments
  resources :posts
  
  root 'posts#index'
  
  get 'posts' => "post#show"
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "login" => "sessions#index"
  get "libraries" => "libraries#index"
  get "tag" => "tags#index"
  get "events" => "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    
    def index
    
    end
    
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>



  <div class="field">
    <%= form.label :event_title %>
    <%= form.text_field :event_title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_area :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="containter">
	<div><h4>Want to add your event to this page?</h4></div>
	<button class="btn btn-success"><a href="mailto:devcommohio@gmail.com?&subject=*Events Inquiry:">Email DevCommOhio the details!</a></button>
	<br>
 <div class="row">
 	<br>
		<div class="col-md-4">
			<div id="eventbrite-widget-container-49555874956">
			<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script>
			<script type="text/javascript">
			    var exampleCallback = function() {
			        console.log('Order complete!');
			    };
			    window.EBWidgets.createWidget({
			        // Required
			        widgetType: 'checkout',
			        eventId: '49555874956',
			        iframeContainerId: 'eventbrite-widget-container-49555874956',
			        // Optional
			        iframeContainerHeight: 50,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
			        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
			    });
			</script>
			</div>
		</div>
		<div class="col-md-4">
			<div id="eventbrite-widget-container-49647357583">

			<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script>

			<script type="text/javascript">
				var exampleCallback = function() {
				        console.log('Order complete!');
				    };

				window.EBWidgets.createWidget({
				        // Required
				        widgetType: 'checkout',
				        eventId: '49647357583',
				        iframeContainerId: 'eventbrite-widget-container-49647357583',

				        // Optional
				        iframeContainerHeight: 50,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
				        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
				});
			</script>
			</div>
		</div>
		<div class="col-md-4">
			<div id="eventbrite-widget-container-49612962707"></div>

			<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script>

			<script type="text/javascript">
			    var exampleCallback = function() {
			        console.log('Order complete!');
			    };

			    window.EBWidgets.createWidget({
			        // Required
			        widgetType: 'checkout',
			        eventId: '49612962707',
			        iframeContainerId: 'eventbrite-widget-container-49612962707',

			        // Optional
			        iframeContainerHeight: 425,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
			        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
			    });
				</script>
		</div>
	</div>
 </div>
</div>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.event_title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @event.link.html_safe %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @event.tag %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @event.date %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> 
<%= link_to 'Back', events_path %>